In [1]:
from helper import run_times_list
import numpy as np

In [2]:
# Print the run_times_list
print(run_times_list)

# Print the length of this list
print(f'\nThe length of the list is {len(run_times_list)}')

[[12.46, 16.15, 13.2, 17.78, 12.09, 11.85, 7.64, 15.95, 11.7, 12.28], [11.9, 11.24, 12.2, 12.44, 15.32, 13.76, 10.39, 12.8, 13.63, 16.73], [9.48, 12.7, 17.86, 11.94, 9.15, 10.68, 15.85, 15.57, 15.02, 12.3], [10.66, 13.06, 12.03, 14.4, 13.21, 10.76, 11.03, 10.59, 15.26, 13.55], [10.48, 14.28, 10.1, 11.97, 11.57, 7.62, 11.6, 8.86, 11.87, 13.82], [11.11, 12.58, 10.37, 10.83, 15.19, 14.82, 13.03, 15.1, 13.76, 12.82], [13.79, 11.01, 10.94, 11.8, 11.52, 11.07, 14.59, 12.81, 15.91, 11.61]]

The length of the list is 7


In [3]:
### edTest(test_1) ###
## DO NOT REMOVE ABOVE LINE ##

# Store this list as a numpy array
runs_array=np.array(run_times_list)
runs_array

array([[12.46, 16.15, 13.2 , 17.78, 12.09, 11.85,  7.64, 15.95, 11.7 ,
        12.28],
       [11.9 , 11.24, 12.2 , 12.44, 15.32, 13.76, 10.39, 12.8 , 13.63,
        16.73],
       [ 9.48, 12.7 , 17.86, 11.94,  9.15, 10.68, 15.85, 15.57, 15.02,
        12.3 ],
       [10.66, 13.06, 12.03, 14.4 , 13.21, 10.76, 11.03, 10.59, 15.26,
        13.55],
       [10.48, 14.28, 10.1 , 11.97, 11.57,  7.62, 11.6 ,  8.86, 11.87,
        13.82],
       [11.11, 12.58, 10.37, 10.83, 15.19, 14.82, 13.03, 15.1 , 13.76,
        12.82],
       [13.79, 11.01, 10.94, 11.8 , 11.52, 11.07, 14.59, 12.81, 15.91,
        11.61]])

### The data in the `runs_array`  ndarray is structured as follows,

|           | Practice 1 | Run 1 | Practice 2 | Run 2 | Practice 3 | Run 3 | Practice 4 | Run 4 | Practice 5 | Run 5 |
|-----------|------------|--------|------------|--------|------------|-------|------------|-------|------------|-------|
| **Kuldeep**    |            |        |            |        |            |       |            |       |            |       |
| **Sheetal**   |            |        |            |        |            |       |            |       |            |       |
| **Anshika**     |            |        |            |        |            |       |            |       |            |       |
| **Pavlos**    |            |        |            |        |            |       |            |       |            |       |
| **Nawang**   |            |        |            |        |            |       |            |       |            |       |
| **Karthiga**  |            |        |            |        |            |       |            |       |            |       |
| **Chaitanya** |            |        |            |        |            |       |            |       |            |       |


In [4]:
# print the shape of the array

runs_array.shape

(7, 10)

### ⏸ How many rows are present and what does each row represent?
#### A) 7, each row represents the times taken to complete alternating practice and actual runs by a member.
#### B) 10, each row represents the times taken to complete a run by every member. 
#### C) 10, each row represents the times taken to complete alternating practice and actual runs by a member.
#### D) 7, each row represents the times taken to complete a run by every member.

In [5]:
### edTest(test_2) ###
## DO NOT REMOVE ABOVE LINE ##

answer='A'

## Make seperate arrays for practice runs and actual runs

In [6]:
### edTest(test_3) ###
## DO NOT REMOVE ABOVE LINE ##

#slice the array to contain only practice runs
practice_array=runs_array[:, [0,2,4,6,8] ] # this is same as runs_array[:, ::2]

#print the shape of the array
print(f'Shape : {practice_array.shape}')
practice_array

Shape : (7, 5)


array([[12.46, 13.2 , 12.09,  7.64, 11.7 ],
       [11.9 , 12.2 , 15.32, 10.39, 13.63],
       [ 9.48, 17.86,  9.15, 15.85, 15.02],
       [10.66, 12.03, 13.21, 11.03, 15.26],
       [10.48, 10.1 , 11.57, 11.6 , 11.87],
       [11.11, 10.37, 15.19, 13.03, 13.76],
       [13.79, 10.94, 11.52, 14.59, 15.91]])

In [7]:
### edTest(test_4) ###
## DO NOT REMOVE ABOVE LINE ##

#slice the array to contain only actual runs
actual_runs_array=runs_array[:,1 ::2 ]

#print the shape of the array
print(f'Shape : {actual_runs_array.shape}')
actual_runs_array

Shape : (7, 5)


array([[16.15, 17.78, 11.85, 15.95, 12.28],
       [11.24, 12.44, 13.76, 12.8 , 16.73],
       [12.7 , 11.94, 10.68, 15.57, 12.3 ],
       [13.06, 14.4 , 10.76, 10.59, 13.55],
       [14.28, 11.97,  7.62,  8.86, 13.82],
       [12.58, 10.83, 14.82, 15.1 , 12.82],
       [11.01, 11.8 , 11.07, 12.81, 11.61]])

## Total time taken by each member to complete the practice runs.

## Time it took on an average to complete each practice run.

In [8]:
### edTest(test_5) ###
## DO NOT REMOVE ABOVE LINE ##

# Calculate the sum of run times of all the practice runs for each member

sum_practice_array=np.sum(practice_array, axis=1)

# Print the shape of the array
print(f'Shape of the array is {sum_practice_array.shape}')
sum_practice_array

Shape of the array is (7,)


array([57.09, 63.44, 67.36, 62.19, 55.62, 63.46, 66.75])

In [9]:
### edTest(test_6) ###
## DO NOT REMOVE ABOVE LINE ##

#find the average time it took to complete each practice run by all members.
# Hint: Perform mean along columns
mean_practice_array=np.mean(practice_array, axis = 0)

# Print the shape of the array
print(f'Shape of the array is {mean_practice_array.shape}')
mean_practice_array

Shape of the array is (5,)


array([11.41142857, 12.38571429, 12.57857143, 12.01857143, 13.87857143])

## Let's see who the winner is.

In [10]:
### edTest(test_7) ###
## DO NOT REMOVE ABOVE LINE ##

# Calculate the total times it took for each member to complete all the actual runs.

actual_runs_sum= np.sum(actual_runs_array , axis = 1)

# Print the shape of the array
print(f'Shape of the array is {actual_runs_sum.shape}')
actual_runs_sum

Shape of the array is (7,)


array([74.01, 66.97, 63.19, 62.36, 56.55, 66.15, 58.3 ])

In [11]:
### edTest(test_8) ###
## DO NOT REMOVE ABOVE LINE ##

# inspect the array and report who has completed all the actual runs in least time


winner='Nawang'

### 🆓️ ⏸ Pause & think
In competitions, the winner would be the one who has completed most number of runs in least time instead of the one completing all the runs in least time.

If you were to find the winner based on this, how would you achieve this and who would be the winner?

In [12]:
### YOUR CODE HERE ###

actual_runs_mean = np.mean(actual_runs_array,axis = 1)
print(f'Shape of the array is {actual_runs_mean.shape}')
actual_runs_mean


Shape of the array is (7,)


array([14.802, 13.394, 12.638, 12.472, 11.31 , 13.23 , 11.66 ])